# Generated by Django 4.2.6 on 2023-12-04 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_save', models.CharField(blank=True, default='#0c854b66', max_length=100, null=True)),
                ('reg_name', models.CharField(max_length=30)),
                ('reg_date', models.DateTimeField(verbose_name='Dates of payment')),
                ('amount', models.IntegerField(default=None)),
                ('currency', models.CharField(max_length=30)),
                ('frequency', models.CharField(max_length=30)),
                ('frequency_int', models.IntegerField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
