# Generated by Django 4.2.8 on 2023-12-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regpay',
            name='reg_date',
            field=models.DateField(verbose_name='Dates of payment'),
        ),
    ]
