# Generated by Django 4.2.6 on 2023-11-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_category_color_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='currently_spent',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='category',
            name='the_limit',
            field=models.IntegerField(default=None),
        ),
    ]
