# Generated by Django 4.2.6 on 2023-11-21 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_category_currently_spent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color_save',
            field=models.CharField(default='#0c854b66', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='currently_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='date_of_rent',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of rent'),
        ),
        migrations.AlterField(
            model_name='category',
            name='due_date',
            field=models.DateField(verbose_name='Due date'),
        ),
        migrations.AlterField(
            model_name='category',
            name='the_limit',
            field=models.IntegerField(default=0),
        ),
    ]
