# Generated by Django 4.2.5 on 2023-11-22 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_mydebts_othersdebts_delete_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydebts',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='othersdebts',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mydebts',
            name='date_of_borrowing',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 22, 15, 10, 37, 338128)),
        ),
        migrations.AlterField(
            model_name='othersdebts',
            name='date_of_borrowing',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 22, 15, 10, 37, 339126)),
        ),
    ]
