# Generated by Django 4.2.7 on 2023-11-26 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_category_color_save_and_more'),
        ('wallet', '0006_mydebts_is_closed_othersdebts_is_closed_and_more'),
    ]

    operations = [
    ]
