# Generated by Django 4.2.5 on 2023-12-05 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_alter_mydebts_date_of_borrowing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mydebts',
            name='date_of_borrowing',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 5, 23, 19, 6, 618078)),
        ),
        migrations.AlterField(
            model_name='othersdebts',
            name='date_of_borrowing',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 5, 23, 19, 6, 618078)),
        ),
    ]
