# Generated by Django 4.2.8 on 2023-12-04 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_alter_mydebts_date_of_borrowing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydebts',
            name='date_of_borrowing',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 4, 14, 43, 58, 384843)),
        ),
        migrations.AlterField(
            model_name='othersdebts',
            name='date_of_borrowing',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 4, 14, 43, 58, 384843)),
        ),
    ]
