# Generated by Django 4.2.8 on 2023-12-04 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_alter_mydebts_date_of_borrowing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_expended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mydebts',
            name='date_of_borrowing',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 4, 15, 55, 28, 943202)),
        ),
        migrations.AlterField(
            model_name='othersdebts',
            name='date_of_borrowing',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 4, 15, 55, 28, 943202)),
        ),
    ]
