# Generated by Django 4.2.8 on 2023-12-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_notification_is_checked_and_more'),
        ('wallet', '0014_category_is_expended_alter_mydebts_date_of_borrowing_and_more'),
    ]

    operations = [
    ]
