# Generated by Django 4.2.8 on 2023-12-06 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_alter_mydebts_date_of_borrowing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='mydebts',
            name='date_of_borrowing',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 7, 0, 26, 0, 72474)),
        ),
        migrations.AlterField(
            model_name='othersdebts',
            name='date_of_borrowing',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 7, 0, 26, 0, 72474)),
        ),
    ]
